### ISSUE TITLE
show how to download image on crop

### ISSUE THREAD

**Issue by codetricity** [codetricity/ricoh-viewer#1]
in features.

the crop button will save to local storage.  Show how to open up the local file in a local viewer.

**Comment by jcasman** [comment]
This means just showing a screenshot of the local image picker (macOS) window, and the ability to save to where you want locally, correct?

**Comment by codetricity** [comment]
@jcasman yes, that is exactly what I am suggesting.

If you have implemented this feature, please close the issue.
